CREATE TABLE [dbo].[JobTitle] (
    [JobTitleID] NVARCHAR (128) NOT NULL,
    [JobTitle]   NVARCHAR (128) NULL,
    CONSTRAINT [PK__Position__60BB9A593A68FD27] PRIMARY KEY CLUSTERED ([JobTitleID] ASC),
    CONSTRAINT [UQ__Position__E46AEF429361151E] UNIQUE NONCLUSTERED ([JobTitle] ASC)
);

